receivers:
    otlp:
      protocols:
        http:
          endpoint: 0.0.0.0:4318
        grpc:
          endpoint: 0.0.0.0:4317

exporters:
    signalfx:
      access_token: ${SPLUNK_ACCESS_TOKEN}  #  
      access_token_passthrough: true
      realm: us1
      timeout: 5s
      max_idle_conns: 80
    debug:
      verbosity: detailed
    # Traces
    sapm:
      access_token: "${SPLUNK_ACCESS_TOKEN}"
      endpoint: "https://ingest.us1.signalfx.com/v2/trace"
      sending_queue:
        num_consumers: 32

processors:
    batch:

extensions:
    health_check:
      endpoint: 0.0.0.0:13133
    pprof:
      endpoint: :1888
    zpages:
      endpoint: :55679

service:
    telemetry:
      logs:
        level: debug
    extensions: [pprof, zpages, health_check]
    pipelines:
      metrics:
        receivers: [otlp]
        processors: [batch]
        exporters: [debug,signalfx]
      traces:
        receivers: [otlp]
        processors:
        - batch
        #- resource/add_environment
        exporters: [sapm]

